In [ ]:
#Employee Class
class Employee:
    num_of_employees = 0

    #initializing the attributes
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.num_of_employees += 1

    #Average Salary Method
    def averageSalary(self, employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees)
#Full Time Employee Class - Super Class
class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, employment_type):
        super().__init__(name, family, salary, department)
        self.employment_type = employment_type

# Instances of Employee class
employee1 = Employee("pravs", 3, 50000, "data analyat")
employee2 = Employee("shankar", 4, 80000, "developer")

# Instances of FulltimeEmployee class
fulltime1 = FulltimeEmployee("Ammu", 5, 90000, "manager", "FullTime")
fulltime2 = FulltimeEmployee("sanju", 6, 100000, "HR", "FullTime")
fulltime3 = FulltimeEmployee("manish", 4, 40000, "jr. software", "FullTime")

# Call member functions
employees = [employee1, employee2, fulltime1, fulltime2, fulltime3]
avgSalary = employee1.averageSalary(employees)

print("Total Employees:", Employee.num_of_employees)
print("Average Salary:", avgSalary)



Total Employees: 5
Average Salary: 72000.0


In [ ]:
#import numpy
import numpy as np
x = np.arange(1,21,dtype=float) #vector size is 1-20
print ("vector:",x)
x=x.reshape(4,5)
print("reshape array to 4 by 5:",x)
def replace(x):
    a=x
    a[:,np.argmax(x, axis=1)] = 0
    return a
result = replace(x)
print("replace the max in each row by 0 (axis=1):",result)


vector: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
reshape array to 4 by 5: [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]
replace the max in each row by 0 (axis=1): [[ 1.  2.  3.  4.  0.]
 [ 6.  7.  8.  9.  0.]
 [11. 12. 13. 14.  0.]
 [16. 17. 18. 19.  0.]]
